#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (c) 2026 Huawei Technologies Co., Ltd.

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../..)

APP = urma_perf

include $(SPDK_ROOT_DIR)/mk/nvme.libtest.mk

SYS_LIBS += -ldl
